<<<<<<< HEAD
# Site settings
title: Frances Siver - MS, RDN, LDN, CLT
email: rdn@fcsiver.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fcsiver.com" # the base hostname & protocol for your site
twitter_username: 
github_username:

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Registered Dietitian Nutritionist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
=======
baseurl:
theme: jekyll-theme-time-machine
>>>>>>> origin/master
